# Generated by Django 5.2.8 on 2025-11-12 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_date', models.DateField(unique=True)),
                ('day_name', models.CharField(max_length=10)),
                ('hebrew_date', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('holiday_name', models.CharField(blank=True, default='empty', max_length=64)),
                ('holiday_type', models.CharField(blank=True, default='empty', max_length=64)),
                ('open_staus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depth', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=25)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceCovering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HoodSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Layouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='layouts/')),
            ],
        ),
        migrations.CreateModel(
            name='Masks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MaskSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('size_full', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipeLength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TracheaSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panelPosition', models.CharField(null=True)),
                ('appointmentStatus', models.CharField(default='SCHE', max_length=4)),
                ('dateID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oxychai_app.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='patient',
            fields=[
                ('personID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, max_length=64)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('req_sess', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('sizeId', models.IntegerField(blank=True, null=True)),
                ('cost_pennys', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('carer', models.BooleanField(default=False)),
                ('extras', models.CharField(blank=True, max_length=64, null=True)),
                ('depth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oxychai_app.depth')),
                ('mask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oxychai_app.masks')),
                ('noteID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oxychai_app.notes')),
                ('pipe_length', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='oxychai_app.pipelength')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyPayed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStamp', models.DateTimeField(auto_now_add=True)),
                ('amountPayed', models.IntegerField()),
                ('appointmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='oxychai_app.appointment')),
                ('noteID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oxychai_app.notes')),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oxychai_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyOwed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStamp', models.DateTimeField(auto_now_add=True)),
                ('amountOwed', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
                ('appointmentID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oxychai_app.appointment')),
                ('patientID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oxychai_app.patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxychai_app.patient'),
        ),
        migrations.CreateModel(
            name='appointmentLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oxychai_app.calendar')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oxychai_app.layouts')),
                ('sessionTime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oxychai_app.time')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='sessionTime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='oxychai_app.time'),
        ),
    ]
