# Generated by Django 5.2.8 on 2025-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxychai_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='panelPosition',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
