# Generated by Django 5.2.8 on 2025-11-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxychai_app', '0002_alter_appointment_panelposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='panelPosition',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='hebrew_date',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='holiday_name',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='holiday_type',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='the_date',
            field=models.DateField(db_index=True, unique=True),
        ),
    ]
