# Generated by Django 5.2.8 on 2025-11-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oxychai_app', '0003_alter_appointment_panelposition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='maintenance_status',
            field=models.BooleanField(default=False),
        ),
    ]
